# Generated by Django 3.2.7 on 2021-09-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0005_alter_address_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='address_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='UK', max_length=100),
        ),
    ]
